- package:
  - name: reinforce-zoo
  - section:
    - name: exe:egreedy-bandits-example
    - message:
      - name: Module not compiled
      - module: RandomAgent
    - message:
      - name: Redundant build-depends entry
      - depends: reinforce-algorithms
  - section:
    - name: exe:qtable-cartpole-example
    - message:
      - name: Redundant build-depends entry
      - depends: reinforce
  - section:
    - name: exe:qtable-cartpole-example exe:qtable-frozenlake-example
    - message:
      - name: Module reused between components
      - module: Main
  - section:
    - name: exe:random-agent-example
    - message:
      - name: Module not compiled
      - module: EGreedy

