- package:
  - name: reinforce-algorithms
  - section:
    - name: test:spec
    - message:
      - name: Redundant build-depends entry
      - depends:
        - QuickCheck
        - reinforce
        - reinforce-algorithms
        - reinforce-environments
        - reinforce-prelude
- package:
  - name: reinforce-zoo
  - section:
    - name: exe:egreedy-bandits-example
    - message:
      - name: Module not compiled
      - module:
        - Agents.QTable.CartPoleSpec
        - Agents.QTable.FrozenLakeSpec
        - RandomAgent
    - message:
      - name: Redundant build-depends entry
      - depends: reinforce-algorithms
  - section:
    - name: exe:random-agent-example
    - message:
      - name: Module not compiled
      - module:
        - Agents.QTable.CartPoleSpec
        - Agents.QTable.FrozenLakeSpec
        - EGreedyBandits

