name: reinforce-agents
version: 0.1.0.0

ghc-options: -Wall

default-extensions:
  - BangPatterns
  - LambdaCase
  - OverloadedStrings
  - ViewPatterns
  - NoImplicitPrelude

dependencies:
  - base
  - reinforce
  - hmatrix
  - containers
  - unordered-containers
  - bytestring
  - vector
  - dlist
  - hashable
  - monad-loops
  - microlens-platform
  - mtl
  - mwc-random
  - safe-exceptions
  - text
  - statistics

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - reinforce-agents
      - hspec
      - QuickCheck
