name:        reinforce
version:     0.0.0.1
synopsis:    a refinforcement learning framework in Haskell
description: Please see README.md
category:    Reinforcement learning, machine learning, artificial intelligence
author:      Sentenai, Inc.
maintainer:  sam@sentenai.com
github:      Sentenai/reinforce
license:     BSD3
copyright:   2017 Sentenai, Inc.

default-extensions:
  - NoImplicitPrelude
  - MultiParamTypeClasses
  - OverloadedStrings
  - LambdaCase
  - TypeFamilies

dependencies:
  - aeson
  - base
# - binary
# - bytestring
  - containers
  - dlist
  - hashable
  - hmatrix
  - http-client
# - microlens-platform
  - mtl
  - mwc-random
  - primitive
  - safe-exceptions
  - servant-client
  - statistics
  - text
  - unordered-containers
  - vector

library:
  source-dirs: src
  dependencies:
    - gym-http-api


executables:
  random-agent-example:
    source-dirs: examples
    main: RandomAgent.hs
    dependencies:
      - reinforce



# tests:
#   spec:
#     source-dirs: test
#     main: Spec.hs
#     dependencies:
#       - hspec
#       - QuickCheck


