name:        reinforce
version:     0.0.0.1
synopsis:    a refinforcement learning framework in Haskell
description: Please see README.md
category:    Reinforcement learning, machine learning, artificial intelligence
author:      Sentenai, Inc.
maintainer:  sam@sentenai.com
github:      Sentenai/reinforce
license:     BSD3
copyright:   2017 Sentenai, Inc.

default-extensions:
  - NoImplicitPrelude
  - MultiParamTypeClasses
  - OverloadedStrings
  - LambdaCase
  - TypeFamilies

dependencies:
  - aeson           >  1.0      && <= 1.2
  - base            >  4.9      && <= 4.10
  - dlist           == 0.8.0.2
  - hashable        >= 1.2.5.0  && <= 1.2.6.1
  - hmatrix         == 0.18.0.0
  - http-client     == 0.5.6.1
  - mtl             == 2.2.1
  - mwc-random      == 0.13.5.0
  - primitive       == 0.6.1.0
  - safe-exceptions == 0.1.5.0
  - servant-client  == 0.9.1.1
  - statistics      == 0.13.3.0
  - text            == 1.2.2.1
  - vector          == 0.11.0.0

library:
  source-dirs: src
  dependencies:
    - gym-http-api


executables:
  random-agent-example:
    source-dirs: examples
    main: RandomAgent.hs
    dependencies:
      - reinforce



# tests:
#   spec:
#     source-dirs: test
#     main: Spec.hs
#     dependencies:
#       - hspec
#       - QuickCheck


