resolver: lts-8.21
flags: {}

packages:
- reinforce
- reinforce-algorithms
- reinforce-environments
- reinforce-environments-gym
- reinforce-prelude
- reinforce-zoo
- location:
    git: https://github.com/stites/gym-http-api.git
    commit: '5b72789'
  subdirs:
    - binding-hs
  extra-dep: true

extra-lib-dirs:
- /usr/local/lib/
- /compat/linux/lib/

extra-include-dirs:
- /usr/local/include/
