name: reinforce-algorithms
version: 0.0.1.0
license-file: LICENSE
ghc-options: -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates
    # -Wmissing-import-lists <-- due to NoImplicitPrelude.

default-extensions:
  - BangPatterns
  - FunctionalDependencies
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  # NoImplicitPrelude
  - OverloadedStrings
  - ScopedTypeVariables
  - ViewPatterns

dependencies:
  - base                  >= 4.9 && < 5.0
  - reinforce             == 0.0.1.0
  - unordered-containers  >= 0.2
  - transformers
  - mtl
  - microlens-platform
  - hashable

library:
  source-dirs: src

# tests:
#   spec:
#     main: Spec.hs
#     source-dirs: test
#     dependencies:
#       - reinforce-algorithms    == 0.0.1.0
#       - reinforce-environments  == 0.0.1.0
#       - hspec                   >= 2.4
#       - QuickCheck              >= 2.9
