resolver: lts-8.12

packages:
- '.'
- '..'
- location:
    git: git@github.com:stites/gym-http-api.git
    commit: '93ce33'
  subdirs:
    - binding-hs
  extra-dep: true

extra-deps: []
flags: {}
extra-package-dbs: []
require-stack-version: ">=1.4"   # for hpack
